#!/bin/bash
LGREEN='\033[1;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color
OK="${LGREEN}OK${NC}"
FAIL="${RED}FAIL${NC}"

diff -u <(head -$1 test/$2-expected.txt|tail -1) <(src/decode-shree-devanagari.py sample/$2.txt|head -$1|tail -1) && RESULT="$OK" || RESULT="$FAIL\n"
printf "TEST LINE $1 of $2:	$RESULT\n"
