#!/bin/bash
LGREEN='\033[1;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color
OK="${LGREEN}OK${NC}"
FAIL="${RED}FAIL${NC}"

BASE_NAME=$1

while shift; do
	[ -z "$1" ] && break
	diff -u <(sed "$1q;d" test/$BASE_NAME-expected.txt) <(sed "$1q;d" sample/$BASE_NAME.txt | src/decode-shree-devanagari.py -) && RESULT="$OK" || RESULT="$FAIL\n"
	printf "TEST LINE $1 of $BASE_NAME:	$RESULT\n"
done
